/**
 * @file dataLoader.js
 * @description Loads and parses the pre-trained ML model output CSVs into
 *              memory at server startup. Provides structured data for the
 *              forecasting service layer.
 *
 * Data sources (generated by the LightGBM + XGBoost ensemble in forecasting.ipynb):
 *   - outputs/future_forecast.csv      → per-store, per-family daily predictions
 *   - outputs/forecast_by_family.csv   → daily predictions aggregated by product family
 *   - outputs/forecast_by_store.csv    → daily predictions aggregated by store
 *   - outputs/detailed_metrics.csv     → model performance metrics
 *   - outputs/cv_fold_metrics.csv      → cross-validation fold metrics
 *   - models/feature_cols.json         → feature columns used in training
 */

const fs = require('fs');
const path = require('path');

/* ── Paths ── */
const OUTPUT_DIR = path.join(__dirname, '..', '..', 'outputs');
const MODEL_DIR  = path.join(__dirname, '..', '..', 'ml_models');

/* ── In-memory cache ── */
let _cache = null;

/**
 * Parse a CSV string into an array of objects (header-keyed).
 * Handles quoted fields containing commas.
 */
function parseCSV(csvString) {
  const lines = csvString.trim().replace(/\r\n/g, '\n').split('\n');
  if (lines.length < 2) return [];

  // Parse header — handle quoted headers
  const header = parseCSVLine(lines[0]);
  const rows = [];

  for (let i = 1; i < lines.length; i++) {
    const values = parseCSVLine(lines[i]);
    const obj = {};
    header.forEach((key, idx) => {
      const val = values[idx] || '';
      // Auto-convert numbers
      const num = Number(val);
      obj[key.trim()] = val !== '' && !isNaN(num) ? num : val.trim();
    });
    rows.push(obj);
  }
  return rows;
}

/**
 * Parse a single CSV line, respecting quoted fields.
 */
function parseCSVLine(line) {
  const result = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      inQuotes = !inQuotes;
    } else if (ch === ',' && !inQuotes) {
      result.push(current);
      current = '';
    } else {
      current += ch;
    }
  }
  result.push(current);
  return result;
}

/**
 * Load a CSV file from disk.
 */
function loadCSV(filename) {
  const filepath = path.join(OUTPUT_DIR, filename);
  if (!fs.existsSync(filepath)) {
    console.warn(`[Forecasting] CSV not found: ${filepath}`);
    return [];
  }
  const raw = fs.readFileSync(filepath, 'utf-8');
  return parseCSV(raw);
}

/**
 * Load model metadata.
 */
function loadModelMeta() {
  const featurePath = path.join(MODEL_DIR, 'feature_cols.json');
  let featureCols = [];
  if (fs.existsSync(featurePath)) {
    featureCols = JSON.parse(fs.readFileSync(featurePath, 'utf-8'));
  }

  // Check model files exist
  const lgbmExists = fs.existsSync(path.join(MODEL_DIR, 'lgbm_model.txt'));
  const xgbExists  = fs.existsSync(path.join(MODEL_DIR, 'xgb_model.ubj'));

  return {
    featureCols,
    models: {
      lgbm: lgbmExists ? 'lgbm_model.txt' : null,
      xgb:  xgbExists  ? 'xgb_model.ubj'  : null,
    },
    ensemble: lgbmExists && xgbExists,
    trainedAt: new Date().toISOString(),
  };
}

/**
 * Aggregate forecast_by_store.csv into daily totals.
 * Each row has: date, store_1, store_2, ..., store_54, TOTAL
 * We use the TOTAL column (last col) for the aggregate daily sales.
 */
function aggregateStoreForecasts(rows) {
  return rows.map(row => {
    // The last numeric column is the TOTAL
    const keys = Object.keys(row);
    const totalKey = keys[keys.length - 1]; // last column
    return {
      date: row.date,
      totalSales: typeof row[totalKey] === 'number' ? row[totalKey] : 0,
    };
  });
}

/**
 * Aggregate forecast_by_family.csv into daily category-level data.
 * Each row: date, AUTOMOTIVE, BABY CARE, ..., TOTAL
 */
function aggregateFamilyForecasts(rows) {
  return rows.map(row => {
    const keys = Object.keys(row);
    const categories = {};
    let total = 0;

    keys.forEach(k => {
      if (k === 'date') return;
      if (k === 'TOTAL') {
        total = row[k] || 0;
      } else {
        categories[k] = row[k] || 0;
      }
    });

    return { date: row.date, categories, total };
  });
}

/**
 * Initialize and cache all forecast data.
 * Called once at server startup.
 */
function initialize() {
  console.log('[Forecasting] Loading ML forecast data...');

  const futureForecast   = loadCSV('future_forecast.csv');
  const forecastByFamily = loadCSV('forecast_by_family.csv');
  const forecastByStore  = loadCSV('forecast_by_store.csv');
  const detailedMetrics  = loadCSV('detailed_metrics.csv');
  const cvFoldMetrics    = loadCSV('cv_fold_metrics.csv');
  const modelMeta        = loadModelMeta();

  const dailyTotals       = aggregateStoreForecasts(forecastByStore);
  const dailyByCategory   = aggregateFamilyForecasts(forecastByFamily);

  _cache = {
    raw: {
      futureForecast,
      forecastByFamily,
      forecastByStore,
      detailedMetrics,
      cvFoldMetrics,
    },
    processed: {
      dailyTotals,
      dailyByCategory,
    },
    modelMeta,
    loadedAt: new Date().toISOString(),
  };

  console.log(`[Forecasting] ✅ Loaded ${futureForecast.length} raw predictions`);
  console.log(`[Forecasting] ✅ ${forecastByStore.length} daily store aggregates`);
  console.log(`[Forecasting] ✅ ${forecastByFamily.length} daily family aggregates`);
  console.log(`[Forecasting] ✅ ${detailedMetrics.length} metric records`);
  console.log(`[Forecasting] ✅ ${cvFoldMetrics.length} CV fold results`);

  return _cache;
}

/**
 * Get cached data (initializes on first call if needed).
 */
function getData() {
  if (!_cache) initialize();
  return _cache;
}

module.exports = { initialize, getData, parseCSV };
