/**
 * @module subcategories
 * @description Subcategory constants for transaction classification.
 * Organized by parent transaction type for validation and lookup.
 */

const EXPENSE_SUBCATEGORIES = Object.freeze({
  ELECTRICITY: 'electricity',
  INTERNET: 'internet',
  GAS: 'gas',
  WATER: 'water',
  MOBILE_BILL: 'mobile_bill',
  RENT: 'rent',
  SALARY: 'salary',
  FUEL: 'fuel',
  TRANSPORT: 'transport',
  MAINTENANCE: 'maintenance',
  REPAIRS: 'repairs',
  OFFICE_SUPPLIES: 'office_supplies',
  STATIONERY: 'stationery',
  MARKETING: 'marketing',
  ADS: 'ads',
  HOSTING: 'hosting',
  SOFTWARE_SUBSCRIPTION: 'software_subscription',
  CLOUD_SERVICES: 'cloud_services',
  DOMAIN: 'domain',
  PRINTING: 'printing',
  INSURANCE: 'insurance',
  BANK_FEE: 'bank_fee',
  TAX: 'tax',
});

const INCOME_SUBCATEGORIES = Object.freeze({
  SERVICE_REVENUE: 'service_revenue',
  PRODUCT_SALES: 'product_sales',
  CONSULTING: 'consulting',
  COMMISSION: 'commission',
  SUBSCRIPTION_INCOME: 'subscription_income',
  INVESTMENT_INCOME: 'investment_income',
});

const ASSET_CATEGORIES = Object.freeze({
  EQUIPMENT: 'equipment',
  FURNITURE: 'furniture',
  LAPTOP: 'laptop',
  VEHICLE: 'vehicle',
  INVENTORY: 'inventory',
  MACHINERY: 'machinery',
});

/**
 * Utility subcategories grouped under expense for utility-specific bill detection.
 */
const UTILITY_SUBCATEGORIES = new Set([
  EXPENSE_SUBCATEGORIES.ELECTRICITY,
  EXPENSE_SUBCATEGORIES.INTERNET,
  EXPENSE_SUBCATEGORIES.GAS,
  EXPENSE_SUBCATEGORIES.WATER,
  EXPENSE_SUBCATEGORIES.MOBILE_BILL,
]);

/**
 * All valid subcategory values across all types.
 */
const ALL_SUBCATEGORIES = new Set([
  ...Object.values(EXPENSE_SUBCATEGORIES),
  ...Object.values(INCOME_SUBCATEGORIES),
  ...Object.values(ASSET_CATEGORIES),
]);

/**
 * Maps keyword hints to subcategories for extraction assistance.
 */
const SUBCATEGORY_KEYWORDS = Object.freeze({
  // Expense keywords
  electricity: EXPENSE_SUBCATEGORIES.ELECTRICITY,
  'electric bill': EXPENSE_SUBCATEGORIES.ELECTRICITY,
  'light bill': EXPENSE_SUBCATEGORIES.ELECTRICITY,
  'power bill': EXPENSE_SUBCATEGORIES.ELECTRICITY,
  wapda: EXPENSE_SUBCATEGORIES.ELECTRICITY,
  kelectric: EXPENSE_SUBCATEGORIES.ELECTRICITY,
  internet: EXPENSE_SUBCATEGORIES.INTERNET,
  wifi: EXPENSE_SUBCATEGORIES.INTERNET,
  broadband: EXPENSE_SUBCATEGORIES.INTERNET,
  nayatel: EXPENSE_SUBCATEGORIES.INTERNET,
  ptcl: EXPENSE_SUBCATEGORIES.INTERNET,
  gas: EXPENSE_SUBCATEGORIES.GAS,
  'gas bill': EXPENSE_SUBCATEGORIES.GAS,
  sui: EXPENSE_SUBCATEGORIES.GAS,
  sngpl: EXPENSE_SUBCATEGORIES.GAS,
  ssgc: EXPENSE_SUBCATEGORIES.GAS,
  water: EXPENSE_SUBCATEGORIES.WATER,
  'water bill': EXPENSE_SUBCATEGORIES.WATER,
  'mobile bill': EXPENSE_SUBCATEGORIES.MOBILE_BILL,
  'phone bill': EXPENSE_SUBCATEGORIES.MOBILE_BILL,
  jazz: EXPENSE_SUBCATEGORIES.MOBILE_BILL,
  zong: EXPENSE_SUBCATEGORIES.MOBILE_BILL,
  telenor: EXPENSE_SUBCATEGORIES.MOBILE_BILL,
  ufone: EXPENSE_SUBCATEGORIES.MOBILE_BILL,
  rent: EXPENSE_SUBCATEGORIES.RENT,
  'office rent': EXPENSE_SUBCATEGORIES.RENT,
  'shop rent': EXPENSE_SUBCATEGORIES.RENT,
  salary: EXPENSE_SUBCATEGORIES.SALARY,
  wages: EXPENSE_SUBCATEGORIES.SALARY,
  payroll: EXPENSE_SUBCATEGORIES.SALARY,
  fuel: EXPENSE_SUBCATEGORIES.FUEL,
  petrol: EXPENSE_SUBCATEGORIES.FUEL,
  diesel: EXPENSE_SUBCATEGORIES.FUEL,
  transport: EXPENSE_SUBCATEGORIES.TRANSPORT,
  travel: EXPENSE_SUBCATEGORIES.TRANSPORT,
  uber: EXPENSE_SUBCATEGORIES.TRANSPORT,
  careem: EXPENSE_SUBCATEGORIES.TRANSPORT,
  maintenance: EXPENSE_SUBCATEGORIES.MAINTENANCE,
  repair: EXPENSE_SUBCATEGORIES.REPAIRS,
  repairs: EXPENSE_SUBCATEGORIES.REPAIRS,
  'office supplies': EXPENSE_SUBCATEGORIES.OFFICE_SUPPLIES,
  stationery: EXPENSE_SUBCATEGORIES.STATIONERY,
  marketing: EXPENSE_SUBCATEGORIES.MARKETING,
  ads: EXPENSE_SUBCATEGORIES.ADS,
  advertisement: EXPENSE_SUBCATEGORIES.ADS,
  advertising: EXPENSE_SUBCATEGORIES.ADS,
  'google ads': EXPENSE_SUBCATEGORIES.ADS,
  'facebook ads': EXPENSE_SUBCATEGORIES.ADS,
  hosting: EXPENSE_SUBCATEGORIES.HOSTING,
  'web hosting': EXPENSE_SUBCATEGORIES.HOSTING,
  subscription: EXPENSE_SUBCATEGORIES.SOFTWARE_SUBSCRIPTION,
  software: EXPENSE_SUBCATEGORIES.SOFTWARE_SUBSCRIPTION,
  cloud: EXPENSE_SUBCATEGORIES.CLOUD_SERVICES,
  aws: EXPENSE_SUBCATEGORIES.CLOUD_SERVICES,
  azure: EXPENSE_SUBCATEGORIES.CLOUD_SERVICES,
  domain: EXPENSE_SUBCATEGORIES.DOMAIN,
  printing: EXPENSE_SUBCATEGORIES.PRINTING,
  insurance: EXPENSE_SUBCATEGORIES.INSURANCE,
  'bank fee': EXPENSE_SUBCATEGORIES.BANK_FEE,
  'bank charges': EXPENSE_SUBCATEGORIES.BANK_FEE,
  tax: EXPENSE_SUBCATEGORIES.TAX,

  // Income keywords
  'service revenue': INCOME_SUBCATEGORIES.SERVICE_REVENUE,
  'client payment': INCOME_SUBCATEGORIES.SERVICE_REVENUE,
  'product sales': INCOME_SUBCATEGORIES.PRODUCT_SALES,
  sales: INCOME_SUBCATEGORIES.PRODUCT_SALES,
  sold: INCOME_SUBCATEGORIES.PRODUCT_SALES,
  consulting: INCOME_SUBCATEGORIES.CONSULTING,
  consultancy: INCOME_SUBCATEGORIES.CONSULTING,
  commission: INCOME_SUBCATEGORIES.COMMISSION,
  'subscription income': INCOME_SUBCATEGORIES.SUBSCRIPTION_INCOME,
  'investment income': INCOME_SUBCATEGORIES.INVESTMENT_INCOME,
  dividend: INCOME_SUBCATEGORIES.INVESTMENT_INCOME,

  // Asset keywords
  equipment: ASSET_CATEGORIES.EQUIPMENT,
  furniture: ASSET_CATEGORIES.FURNITURE,
  laptop: ASSET_CATEGORIES.LAPTOP,
  computer: ASSET_CATEGORIES.LAPTOP,
  vehicle: ASSET_CATEGORIES.VEHICLE,
  car: ASSET_CATEGORIES.VEHICLE,
  bike: ASSET_CATEGORIES.VEHICLE,
  motorcycle: ASSET_CATEGORIES.VEHICLE,
  inventory: ASSET_CATEGORIES.INVENTORY,
  stock: ASSET_CATEGORIES.INVENTORY,
  machinery: ASSET_CATEGORIES.MACHINERY,
  machine: ASSET_CATEGORIES.MACHINERY,
});

module.exports = {
  EXPENSE_SUBCATEGORIES,
  INCOME_SUBCATEGORIES,
  ASSET_CATEGORIES,
  UTILITY_SUBCATEGORIES,
  ALL_SUBCATEGORIES,
  SUBCATEGORY_KEYWORDS,
};
