// config/complianceCalendar.js
// Pakistan-focused compliance obligation templates for FR-10.1
// dueMonths: null = every month; [1,4,7,10] = quarterly Jan/Apr/Jul/Oct
'use strict';

const COMPLIANCE_OBLIGATIONS = [
  // ── Tax ────────────────────────────────────────────────────────────────────
  {
    code: 'FBR_GST',
    name: 'FBR Sales Tax Return',
    description: 'Monthly GST/Sales Tax return filing with FBR',
    category: 'tax',
    dueDayOfMonth: 15,
    dueMonths: null,
    frequencyLabel: 'Monthly',
  },
  {
    code: 'FBR_WHT',
    name: 'FBR Withholding Tax Deposit',
    description: 'Deposit of withholding tax deducted in the previous month',
    category: 'tax',
    dueDayOfMonth: 15,
    dueMonths: null,
    frequencyLabel: 'Monthly',
  },
  {
    code: 'FBR_ADVANCE_TAX',
    name: 'FBR Advance Tax (Quarterly)',
    description: 'Quarterly advance income tax payment (Section 147)',
    category: 'tax',
    dueDayOfMonth: 15,
    dueMonths: [1, 4, 7, 10],
    frequencyLabel: 'Quarterly',
  },
  {
    code: 'FBR_ITR',
    name: 'FBR Annual Income Tax Return',
    description: 'Annual income tax return filing for companies (30 Sep deadline)',
    category: 'tax',
    dueDayOfMonth: 30,
    dueMonths: [9],
    frequencyLabel: 'Annual',
  },
  {
    code: 'FBR_WHT_RETURN',
    name: 'FBR Withholding Tax Statement (Quarterly)',
    description: 'Quarterly withholding tax statement under Section 165',
    category: 'tax',
    dueDayOfMonth: 20,
    dueMonths: [1, 4, 7, 10],
    frequencyLabel: 'Quarterly',
  },
  {
    code: 'FBR_SALES_TAX_RETURN',
    name: 'FBR Sales Tax (GST) Monthly',
    description: 'Monthly Sales Tax Return — 18th of following month',
    category: 'tax',
    dueDayOfMonth: 18,
    dueMonths: null,
    frequencyLabel: 'Monthly',
  },
  {
    code: 'FBR_INCOME_TAX_WITHHOLDING',
    name: 'FBR Income Tax Withholding (Monthly)',
    description: 'Monthly income tax withholding filing under Section 149',
    category: 'tax',
    dueDayOfMonth: 15,
    dueMonths: null,
    frequencyLabel: 'Monthly',
  },
  {
    code: 'FBR_SUPER_TAX',
    name: 'FBR Super Tax (Annual)',
    description: 'Annual super tax payment for high-turnover entities',
    category: 'tax',
    dueDayOfMonth: 31,
    dueMonths: [12],
    frequencyLabel: 'Annual',
  },
  {
    code: 'MINIMUM_TAX',
    name: 'Minimum Tax (Quarterly)',
    description: 'Quarterly minimum tax under Section 113',
    category: 'tax',
    dueDayOfMonth: 15,
    dueMonths: [1, 4, 7, 10],
    frequencyLabel: 'Quarterly',
  },
  {
    code: 'DIVIDEND_WITHHOLDING',
    name: 'Dividend Withholding Tax',
    description: 'Monthly withholding tax on dividends paid',
    category: 'tax',
    dueDayOfMonth: 15,
    dueMonths: null,
    frequencyLabel: 'Monthly',
  },
  {
    code: 'PROFESSIONAL_TAX',
    name: 'Professional Tax',
    description: 'Monthly professional tax deduction and deposit',
    category: 'tax',
    dueDayOfMonth: 15,
    dueMonths: null,
    frequencyLabel: 'Monthly',
  },
  {
    code: 'PROPERTY_TAX',
    name: 'Property Tax (Annual)',
    description: 'Annual property tax filing and payment',
    category: 'tax',
    dueDayOfMonth: 30,
    dueMonths: [6],
    frequencyLabel: 'Annual',
  },
  {
    code: 'EXCISE_DUTY',
    name: 'Federal Excise Duty',
    description: 'Monthly federal excise duty return',
    category: 'tax',
    dueDayOfMonth: 15,
    dueMonths: null,
    frequencyLabel: 'Monthly',
  },
  {
    code: 'CUSTOMS_DUTY',
    name: 'Customs Duty Declaration',
    description: 'Monthly customs duty compliance for import/export businesses',
    category: 'tax',
    dueDayOfMonth: 15,
    dueMonths: null,
    frequencyLabel: 'Monthly',
  },
  // ── Corporate ──────────────────────────────────────────────────────────────
  {
    code: 'SECP_ANNUAL',
    name: 'SECP Annual Return',
    description: 'Annual return filing with SECP under Companies Act 2017',
    category: 'corporate',
    dueDayOfMonth: 31,
    dueMonths: [12],
    frequencyLabel: 'Annual',
  },
  {
    code: 'SECP_HALF_YEAR',
    name: 'SECP Half-Year Accounts',
    description: 'Half-yearly financial accounts submission to SECP',
    category: 'corporate',
    dueDayOfMonth: 30,
    dueMonths: [6],
    frequencyLabel: 'Semi-annual',
  },
  {
    code: 'COMPANIES_ACT_AGM',
    name: 'Companies Act — AGM',
    description: 'Annual General Meeting to be held within 4 months of year-end',
    category: 'corporate',
    dueDayOfMonth: 31,
    dueMonths: [12],
    frequencyLabel: 'Annual',
  },
  {
    code: 'COMPANIES_ACT_ACCOUNTS_FILING',
    name: 'Companies Act — Accounts Filing',
    description: 'Statutory financial accounts filing with SECP (30 Sep deadline)',
    category: 'corporate',
    dueDayOfMonth: 30,
    dueMonths: [9],
    frequencyLabel: 'Annual',
  },
  // ── Labour ─────────────────────────────────────────────────────────────────
  {
    code: 'EOBI',
    name: 'EOBI Contribution',
    description: 'Monthly Employees Old-Age Benefits Institution contribution',
    category: 'labour',
    dueDayOfMonth: 15,
    dueMonths: null,
    frequencyLabel: 'Monthly',
  },
  {
    code: 'SESSI_PESSI',
    name: 'SESSI / PESSI Contribution',
    description: 'Monthly social security contribution (SESSI/PESSI)',
    category: 'labour',
    dueDayOfMonth: 15,
    dueMonths: null,
    frequencyLabel: 'Monthly',
  },
  {
    code: 'EMPLOYEES_SOCIAL_SECURITY',
    name: 'Employees Social Security',
    description: 'Monthly employees social security deposit',
    category: 'labour',
    dueDayOfMonth: 15,
    dueMonths: null,
    frequencyLabel: 'Monthly',
  },
  {
    code: 'WORKERS_WELFARE_FUND',
    name: "Workers' Welfare Fund (Annual)",
    description: "Annual Workers' Welfare Fund contribution (2% of net profit)",
    category: 'labour',
    dueDayOfMonth: 30,
    dueMonths: [6],
    frequencyLabel: 'Annual',
  },
  {
    code: 'WORKERS_PROFIT_PARTICIPATION',
    name: "Workers' Profit Participation Fund (Annual)",
    description: "Annual WPPF contribution — 5% of net profits under Companies Profits (Workers' Participation) Act 1968",
    category: 'labour',
    dueDayOfMonth: 30,
    dueMonths: [9],
    frequencyLabel: 'Annual',
  },
  {
    code: 'PENSION_CONTRIBUTION',
    name: 'Pension / Provident Fund Contribution',
    description: 'Monthly pension/provident fund contribution for eligible employees',
    category: 'labour',
    dueDayOfMonth: 15,
    dueMonths: null,
    frequencyLabel: 'Monthly',
  },
  {
    code: 'GRATUITY_FUND',
    name: 'Gratuity Fund (Annual)',
    description: 'Annual gratuity fund provision and payment compliance',
    category: 'labour',
    dueDayOfMonth: 30,
    dueMonths: [6],
    frequencyLabel: 'Annual',
  },
];

module.exports = { COMPLIANCE_OBLIGATIONS };
